# Generated by Django 4.2.7 on 2023-11-10 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=50)),
                ('fromDate', models.DateField()),
                ('toDate', models.DateField()),
                ('cost', models.IntegerField()),
                ('v_type', models.CharField(max_length=12)),
                ('v_no', models.CharField(max_length=10)),
                ('DriverName', models.CharField(max_length=50)),
                ('DriverContact', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=10, unique=True)),
                ('city', models.CharField(max_length=20)),
                ('v_type', models.CharField(max_length=12)),
                ('isBooked', models.BooleanField(default=False)),
                ('RegDate', models.DateTimeField(auto_now_add=True)),
                ('DriverName', models.CharField(max_length=50)),
                ('DriverContact', models.CharField(max_length=10)),
            ],
        ),
    ]
